name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: burrunan/gradle-cache-action@v1
        name: Build and test
        with:
          job-id: jdk8
          arguments: build
          gradle-version: wrapper